version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "dependency"
      include: "scope"
    open-pull-requests-limit: 20
